Capítulo 3. Trabajando con conjuntos de datos

In [9]:
import h5py
import numpy as np

In [6]:
 f = h5py.File('testfile.hdf5','w')

In [10]:
arr = np.ones((5,2))

In [11]:
f['my dataset'] = arr

In [12]:
dset = f['my dataset']

In [13]:
dset

<HDF5 dataset "my dataset": shape (5, 2), type "<f8">

In [14]:
dset.dtype

dtype('<f8')

In [15]:
dset.shape

(5, 2)

In [16]:
out = dset[...]

In [17]:
out

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
type(out)

numpy.ndarray

In [21]:
dset[1:4,1] = 2.0

In [22]:
dset

<HDF5 dataset "my dataset": shape (5, 2), type "<f8">

In [23]:
out

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
dset[...]

array([[1., 1.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 1.]])

In [25]:
dset = f.create_dataset('test1', (10, 10))#conjunto de datos vacio en f

In [26]:
dset

<HDF5 dataset "test1": shape (10, 10), type "<f4">

In [27]:
dset[...]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [28]:
dset = f['my dataset']

In [29]:
dset[...]

array([[1., 1.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 1.]])

In [30]:
dset = f['test1']

In [31]:
dset[...]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [32]:
dset = f.create_dataset('test2', (10, 10), dtype=np.complex64)

In [33]:
dset[...]#reviso lo creado anteriormente

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]], dtype=complex64)

In [34]:
dset

<HDF5 dataset "test2": shape (10, 10), type "<c8">

In [43]:
dset = f.create_dataset('big_dataset', (1024**3,), dtype=np.float32)#Aquí hay un ejemplo: suponga que desea crear un conjunto de datos 1D que pueda contener 4 gigabytes de muestras de datos de un experimento de larga duración:

In [44]:
ls


config_talk-master/  Imágenes/    PythonDataScienceHandbook-master/
Descargas/           miniconda3/  scipy2017-master/
Documentos/          Música/      snap/
Escritorio/          Plantillas/  test_fast_loading-master/
hdf5-master/         Público/     Vídeos/


In [48]:
dset[0:1024] = np.arange(1024)#escribo en disco

In [46]:
f.flush()#vacio los  buffer

In [47]:
ls


config_talk-master/  Imágenes/    PythonDataScienceHandbook-master/
Descargas/           miniconda3/  scipy2017-master/
Documentos/          Música/      snap/
Escritorio/          Plantillas/  test_fast_loading-master/
hdf5-master/         Público/     Vídeos/


In [50]:
 ls -lh testfile.hdf5

-rw-r--r-- 1 f f 8,1G ene 13 19:48 testfile.hdf5
